config/routes.rb
Rails.application.routes.draw do
  resources :portafolios, except: [:show]
  get 'angular-items', to: 'portafolios#angular'
  get 'portafolio/:id', to: 'portafolios#show', as: 'portafolio_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  root to: 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body

  belongs_to :topic
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern

  def self.image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end
end

app/models/portafolio.rb
class Portafolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.angular
    where(subtitle: 'Angular')
  end

  scope :ruby_on_rails, -> { where(subtitle: 'Ruby on rails') }

  after_initialize :set_defaults

  def set_defaults
    # ||= set the default image only if the image is nil
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder
  validates_presence_of :title, :percent_utilized

  after_initialize :set_defaults

  def set_defaults
    # ||= set the default image only if the image is nil
    self.badge ||= Placeholder.image_generator(height: '250', width: '250')
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portafolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title

  has_many :blogs
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def main
  end

  def user
  end

  def blog
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed' }
    end
  end

  def toggle_status
    if @blog.published?
      @blog.draft!
    elsif @blog.draft?
      @blog.published!
    end
    redirect_to blogs_url, notice: 'Post status has been updated'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def home
  end

  def something
    @else = params[:else]
    @another = params[:another]
  end
end

app/controllers/portafolios_controller.rb
class PortafoliosController < ApplicationController
  def index
    @portafolio_items = Portafolio.all
  end

  def angular
    @angular_portafolio_items = Portafolio.angular
  end

  def new
    @portafolio_item = Portafolio.new
    3.times { @portafolio_item.technologies.build }
  end

  def create
    @portafolio_item = Portafolio.new(portafolio_params)

    respond_to do |format|
      if @portafolio_item.save
        format.html { redirect_to portafolios_path, notice: 'Portafolio was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portafolio_item = Portafolio.find(params[:id])
  end

  def update
    @portafolio_item = Portafolio.find(params[:id])

    respond_to do |format|
      if @portafolio_item.update(portafolio_params)
        format.html { redirect_to portafolios_path, notice: 'Portafolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @portafolio_item = Portafolio.find(params[:id])
  end

  def destroy
    @portafolio_item = Portafolio.find(params[:id])

    @portafolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portafolios_url, notice: 'Portafolio was successfully destroyed.' }
    end
  end

  private
  def portafolio_params
    params.require(:portafolio).permit(:title, :subtitle, :body, technologies_attributes: [:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def missing
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portafolios_helper.rb
module PortafoliosHelper
end

app/views/admin/dashboard/blog.html.erb
<h1>Dashboard#blog</h1>
<p>Find me in app/views/dashboard/blog.html.erb</p>

app/views/admin/dashboard/main.html.erb
<h1>Dashboard#main</h1>
<p>Find me in app/views/dashboard/main.html.erb</p>

app/views/admin/dashboard/user.html.erb
<h1>Dashboard#user</h1>
<p>Find me in app/views/dashboard/user.html.erb</p>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Status</th>
      <th>Options</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoutingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Home page</h1>

app/views/pages/something.html.erb
<h1>We are showing something like <i><%= @else %></i> or maybe like <i><%= @another %></i></h1>

app/views/portafolios/angular.html.erb
<h1>Portafolio Items</h1>
<%= link_to "Create new item", new_portafolio_path %>

<% @angular_portafolio_items.each do |portafolio_item| %>
  <h2><%= link_to portafolio_item.title, portafolio_show_path(portafolio_item) %></h2>
  <h3><%= portafolio_item.subtitle %></h3>
  <p><%= portafolio_item.body %></p>
  <%= image_tag portafolio_item.thumb_image if !portafolio_item.thumb_image.nil? %>
  <!-- <%= image_tag portafolio_item.thumb_image unless portafolio_item.thumb_image.nil? %> -->
  <%= link_to "Edit", edit_portafolio_path(portafolio_item) %>
  <td><%= link_to 'Delete', portafolio_path(portafolio_item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>

app/views/portafolios/edit.html.erb
<h1>Edit this Portafolio Item</h1>

<%= form_with(model: @portafolio_item, local: true) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_area :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portafolios/index.html.erb
<h1>Portafolio Items</h1>
<!-- <a href="portafolios/new">Create new item</a> -->
<%= link_to "Create new item", new_portafolio_path %>

<% @portafolio_items.each do |portafolio_item| %>
  <h2><%= link_to portafolio_item.title, portafolio_show_path(portafolio_item) %></h2>
  <h3><%= portafolio_item.subtitle %></h3>
  <p><%= portafolio_item.body %></p>
  <%= image_tag portafolio_item.thumb_image if !portafolio_item.thumb_image.nil? %>
  <!-- <%= image_tag portafolio_item.thumb_image unless portafolio_item.thumb_image.nil? %> -->
  <%= link_to "Edit", edit_portafolio_path(portafolio_item) %>
  <td><%= link_to 'Delete', portafolio_path(portafolio_item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>

app/views/portafolios/new.html.erb
<h1>Create a new Portafolio</h1>

<%= form_for(@portafolio_item) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_area :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
      <li>
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portafolios/show.html.erb
<%= image_tag @portafolio_item.main_image %>

<h1><%= @portafolio_item.title %></h1>
<h2><em><%= @portafolio_item.subtitle %></em></h2>
<p><%= @portafolio_item.body %></p>

<h2>Technologies used:</h2>
<ol>
  <% @portafolio_item.technologies.each do |t| %>
    <li><%= t.name %></li>
  <% end %>
</ol>

app/views/posts/index.html.erb
<h1>This is Posts</h1>

app/views/posts/missing.html.erb
<h1>Missing link page</h1>

app/views/posts/show.html.erb
<h1>Show page</h1>